CREATE TABLE [dbo].[USER]
(
    [ID] INT NOT NULL PRIMARY KEY IDENTITY,
    [NAME] NVARCHAR(50) NULL,
    [FIRST_NAME] NVARCHAR(50) NULL,
    [USER_NAME] NVARCHAR(50) NOT NULL UNIQUE,
    [PASSWORD] NVARCHAR(MAX) NOT NULL,
    [EMAIL] NVARCHAR(50) NOT NULL,
    [GENDER] INT NULL,
    [ROLE] INT NULL,
);

CREATE TABLE [dbo].[TOURNAMENT]
(
    [ID] INT NOT NULL PRIMARY KEY IDENTITY,
    [NAME] NVARCHAR(50) NOT NULL UNIQUE,
    [TYPE] INT NOT NULL,
    [REG_ENDDATE] DATETIME NOT NULL,
    [STARTDATE] DATETIME NOT NULL,
    [NB_PLAYERS] INT NOT NULL,
    [NB_GAMES] INT NOT NULL,
    [ONGOING] BIT NOT NULL,
)


CREATE TABLE [dbo].[GAME]
(
    [ID] INT NOT NULL PRIMARY KEY IDENTITY,
    [TOURNAMENT_ID] INT FOREIGN KEY REFERENCES [TOURNAMENT]([ID]) NOT NULL,
    [STEP] INT NOT NULL,
    [PLAYER_1] INT FOREIGN KEY REFERENCES [USER]([ID]) NULL,
    [PLAYER_2] INT FOREIGN KEY REFERENCES [USER]([ID]) NULL,
    [PLAYER_3] INT FOREIGN KEY REFERENCES [USER]([ID]) NULL,
    [PLAYER_4] INT FOREIGN KEY REFERENCES [USER]([ID]) NULL,
    [SCORE_1] INT NULL,
    [SCORE_2] INT NULL,
    [SCORE_3] INT NULL,
    [SCORE_4] INT NULL,
    [RANKING_1] INT NULL,
    [RANKING_2] INT NULL,
    [RANKING_3] INT NULL,
    [RANKING_4] INT NULL,
);

CREATE TABLE [dbo].[SUBSCRIPTION]
(
    [Id] INT NOT NULL PRIMARY KEY IDENTITY,
    [TOURNAMENT_ID] INT FOREIGN KEY REFERENCES [TOURNAMENT]([ID]) NOT NULL,
    [USER_ID] INT FOREIGN KEY REFERENCES [USER]([ID]) NOT NULL,
)