CREATE TABLE [dbo].[GAME]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY,
	[TOURNAMENT_ID] INT FOREIGN KEY REFERENCES [TOURNAMENT]([ID]) NOT NULL,
	[STEP] INT NOT NULL,
	[PLAYER_1] INT FOREIGN KEY REFERENCES [USER]([ID]) NOT NULL,
	[PLAYER_2] INT FOREIGN KEY REFERENCES [USER]([ID]) NOT NULL,
	[PLAYER_3] INT FOREIGN KEY REFERENCES [USER]([ID]) NOT NULL,
	[PLAYER_4] INT FOREIGN KEY REFERENCES [USER]([ID]) NOT NULL,
	[SCORE_1] INT NOT NULL,
	[SCORE_2] INT NOT NULL,
	[SCORE_3] INT NOT NULL,
	[SCORE_4] INT NOT NULL,
)
