CREATE TABLE [dbo].[SUBSCRIPTION]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[TOURNAMENT_ID] INT FOREIGN KEY REFERENCES [TOURNAMENT]([ID]) NOT NULL,
	[USER_ID] INT FOREIGN KEY REFERENCES [USER]([ID]) NOT NULL,
)
