CREATE TABLE [dbo].[SUBSCRIPTIONS]
(
	[ID] INT NOT NULL PRIMARY KEY,
	[TOURNAMENT_ID] INT FOREIGN KEY REFERENCES [TOURNAMENT]([ID]) NOT NULL,
	[USER_ID] INT FOREIGN KEY REFERENCES [USER]([ID]) NOT NULL,
)
