CREATE TABLE [dbo].[TOURNAMENT]
(
	[ID] INT NOT NULL PRIMARY KEY,
	[NAME] NVARCHAR(50) NOT NULL UNIQUE,
	[TYPE] INT NOT NULL,
	[REG_ENDDATE] DATE NOT NULL,
	[STARTDATE] DATE NOT NULL,
	[NB_PLAYERS] INT NOT NULL,
	[NB_GAMES] INT NOT NULL,
	[ONGOING] BIT NOT NULL,
)
