CREATE TABLE [dbo].[TOURNAMENT]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY,
	[NAME] NVARCHAR(50) NOT NULL UNIQUE,
	[TYPE] INT NOT NULL,
	[REG_ENDDATE] DATETIME NOT NULL,
	[STARTDATE] DATETIME NOT NULL,
	[NB_PLAYERS] INT NOT NULL,
	[NB_GAMES] INT NOT NULL,
	[ONGOING] BIT NOT NULL,
)
