CREATE TABLE [dbo].[USER]
(
	[ID] INT NOT NULL PRIMARY KEY IDENTITY,
	[NAME] NVARCHAR(50) NULL,
	[FIRST_NAME] NVARCHAR(50) NULL,
	[USER_NAME] NVARCHAR(50) NOT NULL UNIQUE,
	[PASSWORD] NVARCHAR(MAX) NOT NULL,
	[EMAIL] NVARCHAR(50) NOT NULL,
	[GENDER] INT NULL,
	[ROLE] INT NULL,
)
